# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
# lazygit config - nord theme

disableStartupPopups: true
promptToReturnFromSubprocess: false
update:
  method: never
gui:
  showRandomTip: false
  showCommandLog: false
  showBottomLine: false
  showPanelJumps: true
  skipRewordInEditorWarning: true
  expandFocusedSidePanel: true
  statusPanelView: allBranchesLog
  nerdFontsVersion: "3"
  showFileIcons: true
  branchColors:
    "bugfix": "#bf616a"
    "chore": "#616e88"
    "docs": "#a3be8c"
    "feat": "#81a1c1"
    "feature": "#81a1c1"
    "fix": "#bf616a"
  theme:
    activeBorderColor:
      - "#ebcb8b"
      - "bold"
    cherryPickedCommitBgColor:
      - "#434c5e"
    cherryPickedCommitFgColor:
      - "#81a1c1"
    defaultFgColor:
      - "#eceff4"
    inactiveBorderColor:
      - "#81a1c1"
    markedBaseCommitBgColor:
      - "#3b4252"
    markedBaseCommitFgColor:
      - "#ebcb8b"
    optionsTextColor:
      - "#616e88"
    searchingActiveBorderColor:
      - "#ebcb8b"
      - "bold"
    selectedLineBgColor:
      - "#3b4252"
    unstagedChangesColor:
      - "#bf616a"
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
